name: flutter_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.2.0
  logger: ^0.9.1
  dio: ^3.0.0
  provider: ^4.0.2
  flutter_mobx: ^1.1.0
  built_value: ^7.0.9
  cached_network_image: ^2.3.2+1
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  built_value_generator: ^7.0.9
  mobx_codegen: ^1.0.3

flutter:

  uses-material-design: true

